version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - grafana
    restart: unless-stopped

  monitoring-agent:
    build: ./agent
    container_name: monitoring-agent
    environment:
      - DB_HOST=influxdb
      - DB_PORT=8086
      - INFLUXDB_TOKEN=my-super-secret-token
      - INFLUXDB_ORG=monitoring-org
      - INFLUXDB_BUCKET=monitoring
    depends_on:
      influxdb:
        condition: service_healthy
    restart: unless-stopped

  influxdb:
    build: ./database
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=monitoring-org
      - DOCKER_INFLUXDB_INIT_BUCKET=monitoring
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    build: ./grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin-rnp
      - GF_SECURITY_ADMIN_PASSWORD=9ZdTiIlEmrKn7TG5
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local